// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: books_db.sql

package myproject_sqlc

import (
	"context"
)

const DeleteBook = `-- name: DeleteBook :exec

DELETE
FROM books
WHERE id = $1
`

func (q *Queries) DeleteBook(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, DeleteBook, id)
	return err
}

const GetBookAllData = `-- name: GetBookAllData :one

SELECT id, title, author, year, genre, content
FROM books
WHERE id = $1
`

func (q *Queries) GetBookAllData(ctx context.Context, id int32) (Books, error) {
	row := q.db.QueryRow(ctx, GetBookAllData, id)
	var i Books
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.Year,
		&i.Genre,
		&i.Content,
	)
	return i, err
}

const InsertBook = `-- name: InsertBook :one

INSERT INTO books (title, author, year, genre, content)
VALUES ($1, $2, $3, $4, $5) RETURNING id, title, author, year, genre, content
`

type InsertBookParams struct {
	Title   string `db:"title"`
	Author   string `db:"author"`
	Year    int32  `db:"year"`
	Genre   string `db:"genre"`
	Content string `db:"content"`
}

func (q *Queries) InsertBook(ctx context.Context, arg InsertBookParams) (Books, error) {
	row := q.db.QueryRow(ctx, InsertBook,
		arg.Title,
		arg.Author,
		arg.Year,
		arg.Genre,
		arg.Content,
	)
	var i Books
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.Year,
		&i.Genre,
		&i.Content,
	)
	return i, err
}

const ListBooks = `-- name: ListBooks :many

SELECT id, title, author, year, genre, content
FROM books
`

func (q *Queries) ListBooks(ctx context.Context) ([]Books, error) {
	rows, err := q.db.Query(ctx, ListBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Books
	for rows.Next() {
		var i Books
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.Year,
			&i.Genre,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListBooksGenre = `-- name: ListBooksGenre :many


SELECT id, title, author, year, genre, content
FROM books
WHERE genre = $1
`


func (q *Queries) ListBooksGenre(ctx context.Context, genre string) ([]Books, error) {
	rows, err := q.db.Query(ctx, ListBooksGenre, genre)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Books
	for rows.Next() {
		var i Books
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.Year,
			&i.Genre,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateBook = `-- name: UpdateBook :one

UPDATE books
SET title = $2,
    author = $3,
    year = $4,
           genre = $5,
           content = $6
WHERE id = $1 RETURNING id, title, author, year, genre, content
`

type UpdateBookParams struct {
	ID      int32  `db:"id"`
	Title   string `db:"title"`
	Author   string `db:"author"`
	Year    int32  `db:"year"`
	Genre   string `db:"genre"`
	Content string `db:"content"`
}

func (q *Queries) UpdateBook(ctx context.Context, arg UpdateBookParams) (Books, error) {
	row := q.db.QueryRow(ctx, UpdateBook,
		arg.ID,
		arg.Title,
		arg.Author,
		arg.Year,
		arg.Genre,
		arg.Content,
	)
	var i Books
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.Year,
		&i.Genre,
		&i.Content,
	)
	return i, err
}

const UpdateBookContent = `-- name: UpdateBookContent :one

UPDATE books
SET content = $2
WHERE id = $1 RETURNING id, title, author, year, genre, content
`

type UpdateBookContentParams struct {
	ID      int32  `db:"id"`
	Content string `db:"content"`
}

func (q *Queries) UpdateBookContent(ctx context.Context, arg UpdateBookContentParams) (Books, error) {
	row := q.db.QueryRow(ctx, UpdateBookContent, arg.ID, arg.Content)
	var i Books
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.Year,
		&i.Genre,
		&i.Content,
	)
	return i, err
}
